// Generated by https://quicktype.io

export interface ExpenseResponse {
    id?:       string;
    cantidad:  number;
    costo:     number;
    fecha:     string;
    item:      string;
    marca:     string;
    modelo:    number;
    proveedor: string;
}
