// Generated by https://quicktype.io

export interface ExpenseResponse {
    id?:       string;
    cantidad:  string;
    costo:     string;
    fecha:     string;
    item:      string;
    marca:     string;
    modelo:    string;
    proveedor: string;
}
