// Generated by https://quicktype.io

export interface ServiceResponse {
    id:string;
    precio:  string;
    service: string;
}

export interface AddService {
    service: string;
    precio:  string;
}
