// Generated by https://quicktype.io

export interface StockResponse {
    id?:           string;
    cantidad:      number;
    categoria:     string;
    codigo:        number;
    contenidoNeto: string;
    image:         string;
    marca:         string;
    subcategoria:  string;
}
